# fly.toml app configuration file generated for dry-pine-5920 on 2023-08-27T21:22:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dry-pine-5920"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
